Windows API dependency removal
Laurensvanrun/Delphi-Promises pull request #8
Opened 2024-12-09 13:37 UTC by tk-tmssoftware

In order to support cross-platform targeting:
- Removed Windows.Winapi unit
- Removed Spring.Reflection unit
- Replaced WaitForMultipleObjectsEx with a custom WaitForMultipleEvents implementation

2024-12-10 19:12 UTC, Laurensvanrun requested changes

2024-12-10 19:12 UTC, Laurensvanrun commented on Core/Types/Next.Core.Promises.pas
> +    Sleep(10);
You have introduced a performance drop on Windows by sleeping every itteration for 10ms. Please use `WaitForMultipleObjectsEx` on Windows and your method on other operating systems.

2024-12-11 07:26 UTC, tk-tmssoftware commented on Core/Types/Next.Core.Promises.pas
> +    Sleep(10);
Makes sense, added it again with conditional defines for Windows target.

2024-12-11 12:32 UTC, Laurensvanrun approved these changes

2024-12-11 12:32 UTC, merged